export const CHATS_FETCH_STARTED = "CHATS_FETCH_STARTED";
export const CHATS_FETCH_COMPLETED = "CHATS_FETCH_COMPLETED";
export const CHATS_FETCH_FAILED = "CHATS_FETCH_FAILED";
export const CHAT_DELETE_STARTED = "CHAT_DELETE_STARTED";
export const CHAT_DELETE_COMPLETED = "CHAT_DELETE_COMPLETED";
export const CHAT_DELETE_FAILED = "CHAT_DELETE_FAILED";
export const CHAT_ADD_STARTED = "CHAT_ADD_STARTED";
export const CHAT_ADD_COMPLETED = "CHAT_ADD_COMPLETED";
export const CHAT_ADD_FAILED = "CHAT_ADD_FAILED";

export const ACTIVE_CHAT_FETCH_STARTED = "ACTIVE_CHAT_FETCH_STARTED";
export const ACTIVE_CHAT_FETCH_COMPLETED = "ACTIVE_CHAT_FETCH_COMPLETED";
export const ACTIVE_CHAT_FETCH_FAILED = "ACTIVE_CHAT_FETCH_FAILED";